modLoader = "kotlinforforge"
loaderVersion = "[1.0,)"
issueTrackerURL = "https://github.com/Skilles/MobMincer/issues"
updateJSONURL = "https://raw.githubusercontent.com/Skilles/MobMincer/master/update.json"
license = "MIT"

[[mods]]
modId = "mobmincer"
version = "${version}"
displayName = "Mob Mincer"
authors = "Skilles"
description = '''
Harvest mobs over time.
'''
logoFile = "icon.png"

[[mixins]]
config = "mobmincer-common.mixins.json"
[[mixins]]
config = "mobmincer.mixins.json"

[[dependencies.mobmincer]]
modId = "neoforge"
mandatory = true
versionRange = "[20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mobmincer]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mobmincer]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.mobmincer]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[1.5.31,)"
ordering = "BEFORE"
side = "BOTH"