modLoader = "kotlinforforge"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Skilles/MobMincer/issues"
license = "MIT"

[[mods]]
modId = "mobmincer"
version = "${version}"
displayName = "Mob Mincer"
authors = "Skilles"
description = '''
Harvest mobs over time.
'''
logoFile = "assets/mobmincer/icon.png"

[[mixins]]
config = "mobmincer-common.mixins.json"
[[mixins]]
config = "mobmincer.mixins.json"

[[dependencies.mobmincer]]
modId = "neoforge"
mandatory = true
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mobmincer]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mobmincer]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"